language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: QPc7RZkwwThngIGX55nz60Z9wRLhmmJxxIebKEpcgTVz5QuSvR8nwSZ+jcQz78OuGLokjjjCX9xpmNf2eAchRladu2RSU+I+xYtMnnvE4StrA8OY1+3z8DHnW97LRDjfAWHHi8YWZFB07U9UVQuIZvXa2abZw7Ytvud2/YAkdwYIZRzW04Gt+kBUKYagmO8C2mBKkaFWYKHwD0b1oLFqtg0huIZgrchO+OObYQfsl6p69Nw83/X7bcQYidbCvaij63ApBYsHSZbzjK4Xn/kfh98E8Y0IrhJa4JLPAd/OO4Oh9zqX/zjcBIXZP9pIcLKGYvnOLpVzM+2CtFk+sxOJUfB00ueRkxXTJ8ttYXZy6WsK3EMUlY7fsZmCSV0ajs6oOCD95d6Z8q+0gYDrD+5XtUPWq5eqztcbLeo5Waks1DA/BMMZ2UoHAcmrNnUJVhU4H0OuQ6vvd8T9kApeyYGPbfr0v21xfvt3B6O0xuCdJMMXXqNB5iB11fczlZXKPIh11TlrfTjqOZGwaZAy06N/VuL3v93VcE+zP04u0G+Wnzy0PsAeWjLdk3PDNc5f0w0ZeCq61pZk61TGcujYM5FQqL7R9W8gAlPIAv6+PRubNaESE13+X5Nu8Bb+kXrZIpJBglNuiX6zMimvOGuZ5k3IMX3ygqZTRsH4J2hG0/8GhQs=
  app: trabalhotopico
  on:
    repo: BrunoBalzaneloDias/trabalhotopico
